apiVersion: v1
kind: Service
metadata:
  name: hub
  labels:
    app: hub
spec:
  selector:
    app: hub
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: notebook
    port: 8081
    targetPort: 8081